name: Build EasyCode AI Wuzi Dev

on:
  push:
    branches: [ "wuzi/easycode-ai-ide(vs-base-1.96.0)" ]
  workflow_dispatch:

jobs:
  build-linux-server:
    runs-on: ubuntu-latest
    env:
      VSCODE_ARCH: x64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libkrb5-dev python3 python3-pip libx11-dev libxkbfile-dev libsecret-1-dev pkg-config make g++ gcc python3-dev

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-server-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-node-

      - name: Install dependencies
        run: npm ci
        env:
          npm_config_arch: ${{ env.VSCODE_ARCH }}
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Build Linux Server
        run: |
          npm run gulp vscode-reh-linux-${{ env.VSCODE_ARCH }}
          mkdir -p dist/server
          tar -czf dist/server/vscode-reh-linux-${{ env.VSCODE_ARCH }}.tar.gz ../vscode-reh-linux-${{ env.VSCODE_ARCH }}

      - name: Upload Server artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ env.VSCODE_ARCH }}-server
          path: dist/server/vscode-reh-linux-${{ env.VSCODE_ARCH }}.tar.gz
          if-no-files-found: error

